import Vue from 'vue';
import { Loading, Dropdown, DropdownMenu, DropdownItem, MessageBox, Message, Notification, pagination, Tag, Dialog, Button } from 'element-ui';
import Clickoutside from 'element-ui/src/utils/clickoutside';
Vue.directive('clickoutside', Clickoutside);
Vue.use(Tag);
Vue.use(Button);
Vue.use(Dialog);
Vue.use(pagination);
Vue.use(Dropdown);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Loading.directive);
Vue.prototype.$loading = Loading.service;
Vue.prototype.$loading = Loading.service;
Vue.prototype.$msgbox = MessageBox;
Vue.prototype.$alert = MessageBox.alert;
Vue.prototype.$confirm = MessageBox.confirm;
Vue.prototype.$prompt = MessageBox.prompt;
Vue.prototype.$notify = Notification;
Vue.prototype.$message = Message;
